.TH XMQ 1
.SH NAME
xmq \- convert a file in xml format to the xmq format and vice versa.

.SH SYNOPSIS
.B xmq <file_name>

.B xmq -

.SH DESCRIPTION

Xmq reads an xml/xmq file or from stdin and converts it to the xmq/xml
format and writes it to stdout.

For configuration xml files, the xmq format is easier to read and edit
manually than raw xml. Thus you use xmq to view and edit an xml file.
After the edit is done, you use xmq to convert the xmq back to xml.

.SH AUTHOR
Written by Fredrik Öhrström.

.SH COPYRIGHT
Copyright \(co 2019 Fredrik Öhrström and licensed to you under the MIT license.
