.TH XMQ 1
.SH NAME
xmq \- convert a file in xml format to the xmq format and vice versa.

.SH SYNOPSIS
.B xmq [options] <file_name>

.B xmq -

.SH DESCRIPTION

Xmq reads an xml/html/xmq file or from stdin and converts it to the xmq/html/xml
format and writes it to stdout.

.SH OPTIONS

\fB\--color\fR force coloring.

\fB\--mono\fR prevent coloring.

\fB\--compress\fR find common prefixes in tag names.

\fB\--exclude\fR exlude tags.

\fB\--html\fR assume that data is html, even though it does not start with an html tag.

\fB\--nodec\fR do not add the xml/html5 declaration/doctype.

\fB\--nopp\fR do not pretty print xml/html.

\fB\--output=html\fR produce output suitable inclusion between <pre>...</pre> tags.

\fB\--output=terminal\fR write on terminal, use ansi colors if necessary.

\fB\--output=tex\fR produce output suitable for inclusion in tex documents.

\fB\--output=plain\fR produce plain utf8 text.

\fB\-p\fR preserve whitespace when converting from xml to xmq.

\fB\--pp\fR pretty print.

\fB\--nopp\fR do not pretty print.

\fB\-v\fR view only, do not convert between xmq and xml/html.

.SH AUTHOR
Written by Fredrik Öhrström.

.SH COPYRIGHT
Copyright \(co 2019-2020 Fredrik Öhrström and licensed to you under the MIT license.
