#!/bin/sh
if [ "$1" = "" ]
then
    echo "Usage: xmq-less [-v] [--compress] [-x node@attr] <filename.xm[lq]>"
    exit 0
fi

if [ "$1" = "-v" ]
then
    shift 1
    view="-v"
fi

if [ "$1" = "-c" ]
then
    shift 1
    compress="-c"
fi

if [ "$1" = "--sort-attributes" ]
then
    shift 1
    sort="--sort-attributes"
fi

if [ "$1" = "-x" ]
then
    shift 1
    exclude="-x $1"
    shift 1
fi

xmq --color $view $compress $exclude $sort $1 | less -R
