#!/bin/sh
if [ "$1" = "" ]
then
    echo "Usage: xmq-git-diff <filename.xml>"
    exit 0
fi

if [ "$1" = "-c" ]
then
    shift 1
    compress="-c"
fi

if [ "$1" = "-x" ]
then
    shift 1
    exclude="-x $1"
    shift 1
fi

if [ "$1" = "--sort-attributes" ]
then
    shift 1
    sort="--sort-attributes"
fi

xmq $compress $exclude $sort "$1" > /tmp/aa
git show "HEAD:$1" | xmq $compress $exclude $sort - > /tmp/bb
diff /tmp/bb /tmp/aa | colordiff
