#!/bin/sh
if [ "$1" = "" ]
then
    echo "Usage: xmq-git-meld <filename.xml>"
    exit 0
fi

if [ "$1" = "-c" ]
then
    shift 1
    compress="-c"
fi

if [ "$1" = "-x" ]
then
    shift 1
    exclude="-x $1"
    shift 1
fi

xmq $compress $exclude "$1" > /tmp/aa
git show "HEAD:$1" | xmq $compress $exclude - > /tmp/bb
meld /tmp/bb /tmp/aa
