#!/bin/sh
if [ "$1" = "" ]
then
    echo "Usage: xmq-diff <old.xml> <new.xml>"
    exit 0
fi

if [ "$1" = "-c" ]
then
    shift 1
    compress="-c"
fi

if [ "$1" = "-x" ]
then
    shift 1
    exclude="-x $1"
    shift 1
fi

if [ "$1" = "--sort-attributes" ]
then
    shift 1
    sort="--sort-attributes"
fi


oldfile=$(mktemp /tmp/xmq-diff.old.XXXXXX)
newfile=$(mktemp /tmp/xmq-diff.new.XXXXXX)

xmq $compress $exclude $sort "$1" > $oldfile
xmq $compress $exclude $sort "$2" > $newfile
meld $oldfile $newfile
