name: Build Ubuntu
on:
  push:
    branches:
      - master

  pull_request:

jobs:
  job_build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - id: CHECKOUT_SOURCE
      uses: actions/checkout@v3
    - id: APT_UPDATE
      run: sudo apt update
    - id: DISABLE_MAN_PAGES
      run: echo "set man-db/auto-update false" | sudo debconf-communicate; sudo dpkg-reconfigure man-db
    - id: INSTALL_ADDITIONAL_BUILD_DEPENDENCIES
      run: sudo apt install -y eatmydata
    - id: AUTORECONF
      run: autoreconf -fi
    - id: FETCH_DEPS
      run: cd 3rdparty; eatmydata ./fetch_and_build.sh x86_64-pc-linux-gnu
    - id: CONFIGURE
      run: eatmydata ./configure --with-libxml2=3rdparty/libxml2-posix --with-libxslt=3rdparty/libxslt-posix
    - id: MAKE
      run: eatmydata make release
    - id: TEST
      run: eatmydata make test
