name: Build Windows
on:
  push:
    branches:
      - master
      - AddNotOperator

jobs:
  job_build_on_windows:
    runs-on: ubuntu-latest
    steps:
    - id: CHECKOUT_SOURCE
      uses: actions/checkout@v3
    - id: APT_UPDATE
      run: sudo apt update
    - id: INSTALL_ADDITIONAL_BUILD_DEPENDENCIES
      run: sudo apt install -y eatmydata gcc-mingw-w64 wixl wine64
    - id: FETCH_DEPS
      run: cd 3rdparty; ./fetch_and_build.sh x86_64-w64-mingw32
    - id: CONFIGURE
      run: ./configure --host=x86_64-w64-mingw32 --with-libxml2=3rdparty/libxml2-winapi --with-libxslt=3rdparty/libxslt-winapi --with-zlib=3rdparty/zlib-1.3-winapi
    - id: MAKE
      run: make release AT=
